# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 16:21
from __future__ import unicode_literals

from django.db import migrations, models
import web_app.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('f_name', models.CharField(max_length=20, validators=[web_app.fields.validate_lower])),
                ('m_name', models.CharField(max_length=20, validators=[web_app.fields.validate_lower])),
                ('s_name', models.CharField(max_length=20, validators=[web_app.fields.validate_lower])),
                ('id_number', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'tbl_users',
            },
        ),
    ]
